### ISSUE TITLE
CSS: Scrollbars frequently obscure content

### ISSUE THREAD

**Issue by uhlume** [Jormosaurusrex/Diceweaver-issues#2]
When OS and browser are configured to persistently display visible scrollbars by default, resulting controls are positioned so as to overlay and obscure content. (Likely affects multiple UI elements; character sheet is shown below in Chrome Version 90.0.4430.212 64-bit under Windows 10 19042.985.)

![image](https://user-images.githubusercontent.com/1807149/120122041-42b0cd80-c15b-11eb-8c82-c10b6983422d.png)

**Comment by Jormosaurusrex** [comment]
I have developed a fix for this, but it's going to require some whack-a-mole to find individual locations where it's occurring.
