### ISSUE TITLE
CSS: Focus effect on charsheet contenteditable fields obscures entered text

### ISSUE THREAD

**Issue by uhlume** [Jormosaurusrex/Diceweaver-issues#3]
Focus effect sets the field background to white without overriding the default text color, which is also white.

![image](https://user-images.githubusercontent.com/1807149/120122539-498d0f80-c15e-11eb-9884-9e7f1487836b.png)

 Tested in Chrome Version 90.0.4430.212 64-bit/Windows 10 19042.985

**Comment by Jormosaurusrex** [comment]
This was a different bug about font color and is fixed
