### ISSUE TITLE
Users can't add new skills to character sheets

### ISSUE THREAD

**Issue by uhlume** [Jormosaurusrex/Diceweaver-issues#4]
User edits to previously "unusable" (zero-pip) skills on charsheet update local UI as expected, but don't appear to be saved on back-end.

**Tested procedure:**

- Open  main character sheet or Skills flyout. 
- Uncheck "Hide unusable skills" checkbox to show zero-pip skills. 
- Set skill to desired level in local UI (newly-set pips persist but 'calc' field does not recalculate). 
- Re-check "Hide unusable skills"; newly-added skill fails to appear in usable skills list.  
- Disable checkbox again: skill reappears and remains set to user-selected level. 
- Close and re-open character sheet or flyout: user edit undone; skill remains at zero-pip level (update does not appear to stick).

**Comment by uhlume** [comment]
![bugreport_4](https://user-images.githubusercontent.com/1807149/120125885-44848c00-c16f-11eb-901a-adcd86640094.gif)

**Comment by Jormosaurusrex** [comment]
Fixed!  A lot of this got rebuilt.

1) Only show skills you have anyway
2) Add remove is standardized like other collection items
